import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Add parentheses to invoke the function and get the variable
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Updated the RootLayout function to include a main tag for better semantics
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}  {/* Use the children prop here */}
      </body>
    </html>
  );
}
